---
- name: Reload systemd
  command: systemctl daemon-reload
  listen: systemd_reload
  become: true
  
- name: Update apt cache
  apt:
    update_cache: yes
  listen: update_cache

#prometheus
- name: Restart the Prometheus service
  service:
    name: prometheus
    state: restarted
  listen: restart_prometheus

#Grafana
- name: Restart Grafana
  ansible.builtin.systemd:
    name: grafana
    state: restarted
    enabled: yes
  listen: restart_grafana